### ISSUE TITLE
Silently aborts when autoWatch is disabled in CLI

### ISSUE THREAD

**Issue by anshbansal** [caitp/karma-coveralls#26]
Hi I added karma-coveralls in my repo but the reports are not showing up.

Repo https://github.com/anshbansal/linksharing2

https://coveralls.io/builds/2774249

The report showing is for my grails application's test but not for karma tests.

**Comment by anshbansal** [comment]
The docs say that it can take around 4 hours to show up. Why? For the grails plugin it shows up in few minutes.

**Comment by caitp** [comment]
I don't work for coveralls.io, I can't comment on why their infrastructure sometimes takes longer to update. But in this case, I don't think you're going to get the results you want anyways, as you're submitting multiple coverage reports for the same build (I would talk to Coveralls support about this, AFAIK this does not work properly).

If you enable info logging from Karma, you'll get more information about the results of communicating with coveralls

**Comment by caitp** [comment]
Also, it looks like your coveralls account isn't quite set up right (which is why it is saying "can't find source file ....") --- Without contacting support, the only fix I've found for this has been unauthorizing and then re-authorizing the coveralls account for your github repo.

**Comment by caitp** [comment]
One last thing, your karma.conf.js file has `autoWatch=true`, but your Travis configuration tries to override the value on the CLI. This project does not submit coverage reports when `autoWatch` is enabled, which is probably the reason you're not getting a log message. For whatever reason, we're not looking at the CLI-overridden value of the autoWatch flag.

So that seems like a bug, at any rate

**Comment by caitp** [comment]
So, the silent-abort thing is fixed, but after testing a bit it doesn't look like that's what your problem was. I suggest contacting Coveralls support after making sure your environment is configured correctly per the docs, if it's still not working for you.

**Comment by anshbansal** [comment]
- Cannot comment on why infra takes long => Understood
- Sending multiple coverage reports does not work => Will contact coveralls
- enable info logging from Karma => Will try that
- can't find source file ...." => Where does that appear? If you are referring to the stacktrace for "Error reading from object stream" which is due to a problem in a plugin that I am using.
- CLI-overridden value of the autoWatch flag => Perhaps add that to README?
- silent-abort thing is fixed => Does it take time to update on npm/bower?

**Comment by anshbansal** [comment]
Asked coveralls https://github.com/lemurheavy/coveralls-public/issues/544

**Comment by anshbansal** [comment]
BTW are you going to start considering cli arguments?

**Comment by caitp** [comment]
Karma properly applies cli arguments to the config object, so that wasn't the problem. I've updated you'd to log am info love if it gives up for that reason, so try updating to v1.1.0. The only other reason it will give up is if the output from the lcov file is empty,

**Comment by caitp** [comment]
Or if no lcov file is found.

**Comment by anshbansal** [comment]
I am using 1.1.0 already. Tried using the below so that latest is installed. But still got 1.1.0.
npm install karma-coveralls --save-dev
