### ISSUE TITLE
Fails to install on latest NodeJS v10

### ISSUE THREAD

**Issue by webdevbyjoss** [caitp/karma-coveralls#42]
Getting this while running `yarn install`:

     error lcov-result-merger@2.0.0: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
     error Found incompatible module

**Comment by caitp** [comment]
Looks like they fixed this in v3.0.0 (https://github.com/mweibel/lcov-result-merger/releases) --- If you send a pull request to update the dependency, I'll publish the new version.

**Comment by webdevbyjoss** [comment]
Looks like its just as simple as https://github.com/caitp/karma-coveralls/pull/43
