### ISSUE TITLE
Getting error when uploading coverage to coveralls

### ISSUE THREAD

**Issue by jnahas55** [caitp/karma-coveralls#46]
I want to use karma-coveralls plugin in my Vue project, I followed the instructions:

1. Installed the plugin running `npm install karma-coveralls --save-dev`
2. Checked the karma.conf.js

    `reporters: ['spec', 'coverage', 'coveralls'],`

 and 

```
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    }
```
3. Defined an environment variable COVERALLS_REPO_TOKEN containing the repo-token taken from coveralls.io
4. Run `npm run test`, and after my test suite is run, this is what I get:

```
=============================== Coverage summary ===============================
Statements   : 42.97% ( 269/626 )
Branches     : 26.56% ( 17/64 )
Functions    : 42.21% ( 65/154 )
Lines        : 42.97% ( 269/626 )
================================================================================

30 09 2018 14:28:04.129:INFO [coveralls.io]: uploading...
30 09 2018 14:28:04.130:INFO [coveralls.io]: 422 --- {"message":"Couldn't find a repository matching this job.","error":true}
```

Any help would be greatly appreciated  =)

**Comment by caitp** [comment]
I recommend that you open up WireShark, or just add some logging statements to look at `postData` before it's sent (https://github.com/caitp/karma-coveralls/blob/master/lib/index.js#L61), and be sure to double check that the repo token matches.

**Comment by jnahas55** [comment]
It was a missconfiguration on the karma configuration js file (the directory and type were incorrect). After fixing it, my Travis build successfully sent the coverage report to coveralls via this plugin. Thanks caitp!
