### ISSUE TITLE
Support for uploading reports for multiple browsers

### ISSUE THREAD

**Issue by caitp** [caitp/karma-coveralls#5]
I don't really know how this should work yet! But it would be neat.

**Comment by yagoferrer** [comment]
Hey @caitp If I’m not mistaken, the lcov format is not either a browser or language specific. Correct me if I'm wrong but such a feature can't be implemented.

**Comment by caitp** [comment]
this has nothing to do with lcov as a format, it has to do with submitting multiple reports to coveralls when karma generates coverage reports for multiple browsers

**Comment by yagoferrer** [comment]
ohhh! Interesting...

**Comment by yagoferrer** [comment]
Perhaps adding a feature that merges multiple lcov results into one? We can get ideas from here, look:
https://github.com/mweibel/lcov-result-merger
