### ISSUE TITLE
Code coverage report custom directory.

### ISSUE THREAD

**Issue by yagoferrer** [caitp/karma-coveralls#8]
Hey @caitp,
According to [Karma](http://karma-runner.github.io/0.8/config/coverage.html): you can set the directory where code coverage reports are generated like this:
```javascript
    coverageReporter: {
      dir: 'myCustomDir',
      reporters: [
        { type: 'text'},
        { type: 'html'},
        { type: 'lcov'}
      ]
    }
```
This is convenient if you want to setup multiple reports going to the same output directory.

`karma-coveralls` it will only pick up a custom directory with this syntax, otherwise it defaults to `coverage`
```javascript
    coverageReporter: {
      reporters: [
        { type: 'text'},
        { type: 'html'},
        { type: 'lcov', dir: 'myCustomDir'}
      ]
    }
```

I'll send you a PR later, but I wanted to open this issue. :)

**Comment by caitp** [comment]
a PR would be great

**Comment by yagoferrer** [comment]
ok sent!
